site_name: BlockNote-py Documentation
site_description: Python support for BlockNote.js - Convert between BlockNote blocks and various formats
site_author: Rohan Sharma Sitoula
site_url: https://rohansharmasitoula.github.io/blocknote-py/

repo_name: rohansharmasitoula/blocknote-py
repo_url: https://github.com/rohansharmasitoula/blocknote-py

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Basic Usage: getting-started/basic-usage.md
  - Converters:
    - Overview: converters/overview.md
    - BlockNote to HTML: converters/blocknote-to-html.md
    - HTML to BlockNote: converters/html-to-blocknote.md
    - BlockNote to Markdown: converters/blocknote-to-markdown.md
    - Markdown to BlockNote: converters/markdown-to-blocknote.md
    - BlockNote to Dict: converters/blocknote-to-dict.md
    - Dict to BlockNote: converters/dict-to-blocknote.md
  - API Reference:
    - Schema: api/schema.md
    - Converters: api/converters.md
  - Examples:
    - Basic Examples: examples/basic.md
    - Advanced Usage: examples/advanced.md
  - Contributing: contributing.md
  - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rohansharmasitoula/blocknote-py
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/blocknote-py/
